make sure the job fails if ludtwig fails

diff --git a/.github/workflows/storefront.yml b/.github/workflows/storefront.yml
--- a/.github/workflows/storefront.yml
+++ b/.github/workflows/storefront.yml
@@ -68,14 +68,14 @@ jobs:
           image: maltejanz/ludtwig:0.10.0
           options: -v ${{ github.workspace }}:/ludtwig
           run: |
-            pwd
-            ls -lah
             cd ./src/Storefront/Resources/views
             ludtwig .
+            status=$?  # Capture the exit code of ludtwig
             ludtwig --version
             echo "If you want to run this locally install https://github.com/MalteJanz/ludtwig in the version above"
             echo "And then composer run ludtwig:storefront or ludtwig:storefront:fix"
             echo "Alternatively you also can run these in the DevEnv shell"
+            exit $status  # Fail the job if ludtwig . failed
 
 
   jest:
